name: GCP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCP credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > $HOME/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json" >> $GITHUB_ENV

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: my-flask-app-123456   # 👈 replace with your real GCP Project ID
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Authenticate gcloud
        run: gcloud auth activate-service-account --key-file=$HOME/gcp-key.json

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-react-app \
            --source . \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated
